### PR TITLE
Upgrade Typescript to 4.2.4

### PR DESCRIPTION
**Pull request by dingbat**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-firestore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

------

I was working on adding proper typing to the Firestore `update` methods (by making `UpdateData` generic), but it needed some newer Typescript features to work.

Sorry I didn't open an issue first, I figured these changes were pretty straightforward.

The only thing I wasn't sure about here was the `as any` for `pathValue` - this was to allow the test to `delete` the key later on (it needed to be optional, and I wasn't sure about the cleanest way to do that since there is no interface defined for `allSupportedTypesObject`).

### CODE REVIEW

**Comment by schmidt-sebastian** [comment]
@dingbat Thank you for this. I need to verify whether we can accept this PR or whether it is going to break our internal tooling.

@JustinBeckwith - Is this a PR we can take?

**Comment by JustinBeckwith** [comment]
Most likely not.  Changing the version of the TypeScript compiler changes the `d.ts` in ways that can be backwards incompatible with older versions of the TypeScript compiler.  Landing this is a breaking change, and something we should pair with the dropping of Node.js 10.x in a few months.  Tagging in @bcoe so we can coordinate!

**Comment by schmidt-sebastian** [comment]
FWIW We don't use auto-generated types in this repo, so we might be okay here. That being said, manually adding 4.x features to our manual typings is also a breaking change.

**Review by glock47 — CHANGES_REQUESTED** [review]
Data/CmmtSet/924303.csv

**Comment by bcoe** [comment]
we are now on a newer version of typescript 👍

**Pull request closed without merging**
