### PR TITLE
update optional way to getting started with node.js with cloud firestore

### PR DESCRIPTION
**Pull request by noomerzx**
After exprimenting on cloud firestore by following the guide by creating project in cloud platform I've some problem and cannot access firestore db.

So I've creating new project on firebase console instead then go to db section and select the firestore, then generate new config and use the same experimental code [from previous project above] to access firestore and it's work properly.

### CODE REVIEW

**Comment by noomerzx** [comment]
I sign it

**Comment by jmdobry** [comment]
This README is auto-generated, and therefore your changes would be wiped out the next time we re-generate it.

However, you should be able to use Firestore without a Firebase project, I'm investigating.

**Comment by lukesneeringer** [comment]
Unfortunately, we can not accept this PR (our tooling would plow over it).
Did we figure out the Firebase project part?

**Comment by jmdobry** [comment]
@noomerzx You may have run into the problem that Firestore cannot be used in any Google Cloud Platform project that has every used Datastore. They can't both be used in the same project. You'd have to create a new Datastore-less project to use Firestore.

**Comment by stephenplusplus** [comment]
Closing due to age of the issue.

**Pull request closed without merging**
