### PR TITLE
Make DocumentSnapshot .data() generic

### PR DESCRIPTION
**Pull request by polRk**
```
functions.firestore
  .document('agencies/{agencyID}/tasks/{taskID}')
  .onCreate((snapshot:  FirebaseFirestore.DocumentSnapshot<{name: string}>, context) => true);

 FirebaseFirestore.DocumentSnapshot<{name: string}>
```

### CODE REVIEW

**Comment by schmidt-sebastian** [comment]
Thank you for sending this over! This is a feature request that comes around every once in a while (see https://github.com/googleapis/nodejs-firestore/issues/109), but we have so far decided to keep things as is. Out client doesn't know the type of the data that it is returning, and hence any "casting" that we do is not safe. Since there are no guarantees, we would rather make this explicit by returning `any` from `DocumentSnapshot.data()`.

**Comment by polRk** [comment]
But you can add non required generic types , like 
```
class A <D = number> {
}

new A<string>();
new A();
```
If i know, the type of the data, i want use generic. 
And in pull request , i added support generic types to some functions.

**Comment by polRk** [comment]
Add returning `any` - It's a bad practice .

**Comment by Robula** [comment]
This change would be awesome, `data()` _really_ needs to be generic so we can avoid casting all together.

**Comment by mikelehen** [comment]
Just to be clear, there fundamentally has to be a cast here.  The question is whether Firestore would do this for you implicitly or whether the developer has to do it explicitly.  Our current position is that it's better if the developer does it  explicitly so that they are aware there's a non-type-safe operation going on.  

FWIW- Returning `any` is consistent with e.g. the typings TypeScript provides for IndexedDb (https://github.com/Microsoft/TypeScript/blob/84087d0e0a795eee3b1a8cb1988e1285b13cdd5e/lib/lib.dom.d.ts#L9165).

**Comment by fenixsolorzano** [comment]
+1, Dealing with explicit casting is kinda awful, sometimes we end up using strings in our code just to safely do casting:

```ts
const myType: MyTypeInterface = {
  fieldA: snapshot.get('fieldA'),
  fieldB: snapshot.get('fieldB'),
} 
```

It would be awesome if at least the functions that require field names or strings would support some kind of typed parameters by using `keyof T`...

**Pull request closed without merging**
