### PR TITLE
fix: minify proto JSON files

### PR DESCRIPTION
**Pull request by alexander-fenster**
Use the `minifyProtoJson` script from `google-gax` to minify proto JSON files. No one reads those auto-generated files anyway.

### CODE REVIEW

**Comment by alexander-fenster** [comment]
Before:

```
$ ls -lh dev/protos/*.json
-rw-r--r--  1 fenster  primarygroup    76K Sep 12 13:58 dev/protos/admin_v1.json
-rw-r--r--  1 fenster  primarygroup    89K Sep 12 13:58 dev/protos/v1.json
-rw-r--r--  1 fenster  primarygroup    79K Sep 12 13:58 dev/protos/v1_admin.json
-rw-r--r--  1 fenster  primarygroup    88K Sep 12 13:58 dev/protos/v1beta1.json
```

After:

```
$ ls -lh dev/protos/*.json
-rw-r--r--  1 fenster  primarygroup    28K Sep 12 13:59 dev/protos/admin_v1.json
-rw-r--r--  1 fenster  primarygroup    32K Sep 12 13:59 dev/protos/v1.json
-rw-r--r--  1 fenster  primarygroup    29K Sep 12 13:59 dev/protos/v1_admin.json
-rw-r--r--  1 fenster  primarygroup    31K Sep 12 13:59 dev/protos/v1beta1.json
```

**Review by MarkDuckworth — APPROVED** [review]
LGTM? Will this affect debuggability?

**Comment by alexander-fenster** [comment]
Oh, actually, I just realized I can do the same as I did in `google-gax` here. Let's minify the proto JSONs only in the `build` folder, so that they are minified in the distribution (for `npm pack`), but are readable in the repository. Updated the PR. Thanks for reviewing!

**Comment by alexander-fenster** [comment]
Verifying that it actually works as intended:

```
$ npm run compile

> @google-cloud/firestore@6.1.0 precompile
> gts clean

version: 16
Removing build ...

> @google-cloud/firestore@6.1.0 compile
> tsc -p .


> @google-cloud/firestore@6.1.0 postcompile
> node scripts/init-directories.js && cp -r dev/protos build && cp dev/src/v1beta1/*.json build/src/v1beta1/ && cp dev/src/v1/*.json build/src/v1/ && cp dev/conformance/test-definition.proto build/conformance && cp dev/conformance/conformance-tests/*.json build/conformance/conformance-tests && minifyProtoJson

Minifying admin_v1.json...
Minifying v1.json...
Minifying v1_admin.json...
Minifying v1beta1.json...
Minified all proto JSON files successfully.
```

```
$ npm pack
npm notice 
npm notice 📦  @google-cloud/firestore@6.1.0
npm notice === Tarball Contents === 
npm notice 11.4kB  LICENSE                                                     
npm notice 8.2kB   README.md                                              
...
npm notice 29.1kB  build/protos/admin_v1.json
...
npm notice 29.8kB  build/protos/v1_admin.json                                  
npm notice 32.3kB  build/protos/v1.json                                        
npm notice 32.0kB  build/protos/v1beta1.json                                   
...
npm notice === Tarball Details === 
npm notice name:          @google-cloud/firestore                 
npm notice version:       6.1.0                                   
npm notice filename:      @google-cloud/firestore-6.1.0.tgz       
npm notice package size:  623.0 kB                                
npm notice unpacked size: 5.9 MB                                  
npm notice shasum:        be5309cb9e198a7c7465831d6dd54c32e2829cf7
npm notice integrity:     sha512-hXXmXPJtDlcy+[...]mmsRBKFFAF8Ng==
npm notice total files:   159                                     
npm notice 
google-cloud-firestore-6.1.0.tgz
```

Note the size of `npm pack`-ed package in the main branch:

```
npm notice package size:  630.5 kB                                
npm notice unpacked size: 6.1 MB
```

**Review by MarkDuckworth — APPROVED** [review]

**Pull request merged**
